# Generated by Django 5.1.7 on 2025-08-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_file_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='autograde_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='autograde_leniency',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='assignment',
            name='autograde_max_tokens',
            field=models.PositiveIntegerField(default=16000),
        ),
        migrations.AddField(
            model_name='assignment',
            name='autograde_weight_rubric',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='assignment',
            name='autograde_weight_runtime',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='autograde_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='autograde_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=12),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='runner_logs',
            field=models.TextField(blank=True),
        ),
    ]
