# Generated by Django 5.0.7 on 2025-08-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignmentsubmission_graded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='graded_at',
        ),
    ]
