# Generated by Django 5.1.7 on 2025-08-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_remove_assignmentsubmission_graded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='autograde_job_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='autograde_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('await_manual', 'Await manual review')], default='queued', max_length=12),
        ),
    ]
