# Generated by Django 5.1.7 on 2025-08-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_assignment_autograde_job_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='autograde_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
