# Generated by Django 5.0.7 on 2025-09-10 02:15

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_assignment_autograde_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=assignments.models.assignment_upload_path),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(max_length=1024, upload_to=assignments.models.submission_upload_path),
        ),
    ]
