services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped

  unigrading:
    build: .
    container_name: unigrading
    depends_on:
      - minio
    volumes:
      - ./UniGrading:/UniGrading  
    working_dir: /UniGrading
    environment:
      DJANGO_SETTINGS_MODULE: UniGrading.settings
      DATABASE_URL: /UniGrading/db.sqlite3  
      AWS_ACCESS_KEY_ID: Dpa10KF1UZygmxyr36HW
      AWS_SECRET_ACCESS_KEY: ecoN8snDkWsunb6D2R5GPe3sRYp3KflOVLgXZ2zd
      AWS_STORAGE_BUCKET_NAME: files
      AWS_S3_ENDPOINT_URL: http://minio:9000
    ports:
      - "8000:8000"  
    restart: unless-stopped

volumes:
  minio-data:
