version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"    
      - "9001:9001"    
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped

  app:
    image: python:3.10
    container_name: django_app
    depends_on:
      - minio
    volumes:
      - ./UniGrading/UniGrading/db.sqlite3:/app/db.sqlite3  
    environment:
      DATABASE_URL: /app/db.sqlite3
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_STORAGE_BUCKET_NAME: files
      AWS_S3_ENDPOINT_URL: http://minio:9000  
    restart: unless-stopped

volumes:
  minio-data:
