services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped

  # Docker daemon (Docker-in-Docker) used by the worker to run student code
  dind:
    image: docker:27-dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""   # dev convenience; enable TLS for production
    # Pass DNS to the inner dockerd so spawned containers can resolve (pip, apt, etc.)
    command:
      - --host=tcp://0.0.0.0:2375
      - --dns=1.1.1.1
      - --dns=8.8.8.8
    volumes:
      - dind-storage:/var/lib/docker
      - grader-shared:/grader-shared
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

  unigrading:
    build: .
    container_name: unigrading
    depends_on:
      - minio
      - dind
      - redis
    volumes:
      - ./UniGrading:/UniGrading
      - grader-shared:/grader-shared
    working_dir: /UniGrading
    environment:
      DJANGO_SETTINGS_MODULE: UniGrading.settings
      DATABASE_URL: ${DATABASE_URL:-/UniGrading/db.sqlite3}

      # LLM
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      AUTOGRADER_USE_LLM: ${AUTOGRADER_USE_LLM:-1}
      AUTOGRADER_REQUIRE_LLM: ${AUTOGRADER_REQUIRE_LLM:-1}
      OPENAI_TEXT_MODEL: ${OPENAI_TEXT_MODEL:-gpt-5-mini}
      OPENAI_CODE_MODEL: ${OPENAI_CODE_MODEL:-gpt-5-mini}

      # S3 / MinIO
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-minioadmin}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME:-files}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL:-http://minio:9000}

      # Autograder execution
      DOCKER_HOST: tcp://dind:2375
      AUTOGRADER_ENABLE_DOCKER: "1"
      AUTOGRADER_DISABLE_DOCKER: "0"
      AUTOGRADER_ENABLE_LOCAL_EXEC: "0"
      AUTOGRADER_TIMEOUT_SEC: "180"
      AUTOGRADER_MAX_LOG_BYTES: "200000"
      GRADER_SHARED_DIR: /grader-shared

      # Celery / Redis
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}

      # Django misc
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-django-insecure-dev-key}
      DEBUG: ${DEBUG:-1}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-127.0.0.1,localhost,unigrading}
      TIME_ZONE: ${TIME_ZONE:-UTC}
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

  worker:
    build: .
    container_name: unigrading-worker
    depends_on:
      - redis
      - dind
      - minio
    volumes:
      - ./UniGrading:/UniGrading
      - grader-shared:/grader-shared
    working_dir: /UniGrading
    environment:
      DJANGO_SETTINGS_MODULE: UniGrading.settings

      # Autograder execution (worker talks to DinD)
      DOCKER_HOST: tcp://dind:2375
      AUTOGRADER_ENABLE_DOCKER: "1"
      AUTOGRADER_DISABLE_DOCKER: "0"
      AUTOGRADER_ENABLE_LOCAL_EXEC: "0"
      AUTOGRADER_ALLOW_NET_SETUP: "1"        # allow one-time networked setup containers
      AUTOGRADER_TIMEOUT_SEC: "180"
      AUTOGRADER_MAX_LOG_BYTES: "200000"
      GRADER_SHARED_DIR: /grader-shared

      # LLM
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      AUTOGRADER_USE_LLM: ${AUTOGRADER_USE_LLM:-1}
      AUTOGRADER_REQUIRE_LLM: ${AUTOGRADER_REQUIRE_LLM:-1}
      OPENAI_TEXT_MODEL: ${OPENAI_TEXT_MODEL:-gpt-5-mini}
      OPENAI_CODE_MODEL: ${OPENAI_CODE_MODEL:-gpt-5-mini}

      # S3 / MinIO
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-minioadmin}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME:-files}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL:-http://minio:9000}

      # Celery / Redis
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}

      # Django misc
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-django-insecure-dev-key}
      DEBUG: ${DEBUG:-1}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-127.0.0.1,localhost,unigrading}
      TIME_ZONE: ${TIME_ZONE:-UTC}
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command: >
      sh -c "celery -A UniGrading.celery_app worker -l info --concurrency=1 -E"
    restart: unless-stopped

  beat:
    build: .
    container_name: unigrading-beat
    depends_on:
      - redis
    volumes:
      - ./UniGrading:/UniGrading
    working_dir: /UniGrading
    environment:
      DJANGO_SETTINGS_MODULE: UniGrading.settings
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      TIME_ZONE: ${TIME_ZONE:-UTC}
    command: >
      sh -c "celery -A UniGrading.celery_app beat -l info"
    restart: unless-stopped

  flower:
    image: mher/flower:2.0.1
    container_name: flower
    depends_on:
      - redis
    command:
      - "flower"
      - "--broker=redis://redis:6379/0"
      - "--address=0.0.0.0"
      - "--port=5555"
    ports:
      - "5555:5555"
    restart: unless-stopped

volumes:
  minio-data:
  dind-storage:
  grader-shared:
