# Generated by Django 5.1.7 on 2025-03-17 10:36

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='files/'),
        ),
    ]
