# Generated by Django 5.0.7 on 2025-03-26 08:06

import django.db.models.deletion
import storages.backends.s3
import subjects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_file_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=subjects.models.subject_file_upload_path),
        ),
    ]
