# Generated by Django 5.1.2 on 2024-12-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_category_parent_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('subject', 'name')},
        ),
    ]
