# Generated by Django 5.1.7 on 2025-08-29 02:52

import subjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=subjects.models.subject_file_upload_path),
        ),
    ]
