# Generated by Django 5.1.2 on 2024-12-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_category_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
    ]
