# Generated by Django 5.0.7 on 2025-09-10 02:15

import subjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=1024, upload_to=subjects.models.subject_file_upload_path),
        ),
    ]
