# Generated by Django 5.0.7 on 2025-08-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='testattempt',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testattempt')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
